---
- name: Install apache and php
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
    state: present
    update_cache: true

- name: Set index.php as default homepage
  ansible.builtin.lineinfile:
    path: /etc/apache2/mods-enabled/dir.conf
    search_string: DirectoryIndex
    line: "        DirectoryIndex index.php index.html"
    state: present
  notify: Restart apache

- name: Create custom web site dir
  ansible.builtin.file:
    path: "/var/www/{{ apache_website_name }}"
    state: directory
    mode: "0755"

- name: Generate basic html index
  ansible.builtin.template:
    src: index.html
    dest: "/var/www/{{ apache_website_name }}/index.html"
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Generate basic php index
  ansible.builtin.template:
    src: index.php
    dest: "/var/www/{{ apache_website_name }}/index.php"
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Generate VirtualHost config
  ansible.builtin.template:
    src: vhost.conf
    dest: /etc/apache2/sites-available/{{ apache_website_name }}.conf
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Enable website
  ansible.builtin.command:
    cmd: a2ensite {{ apache_website_name }}.conf
    creates: /etc/apache2/sites-enabled/{{ apache_website_name }}.conf
  notify: Restart apache

- name: Disable default website
  ansible.builtin.command:
    cmd: a2dissite 000-default.conf
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Restart apache

- name: Validate configs
  ansible.builtin.command:
    cmd: apache2ctl configtest
  register: apache_validate_config
  changed_when: apache_validate_config.rc != 0

- name: Start and enable apache service
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true

- name: Run notified handlers
  ansible.builtin.meta: flush_handlers
