---
- name: Install apache and php
  ansible.builtin.apt:
    name:
      - apache2
      - libapache2-mod-php
      - php
      - php-mysql
    state: present
    update_cache: true

- name: Set index.php as default homepage
  ansible.builtin.lineinfile:
    path: /etc/apache2/mods-enabled/dir.conf
    search_string: DirectoryIndex
    line: "        DirectoryIndex index.php index.html"
    state: present
  notify: Restart apache

- name: Create custom web site dir
  ansible.builtin.file:
    path: "/var/www/{{ apache_website_name }}"
    state: directory
    mode: "0755"

- name: Create basic html index
  ansible.builtin.copy:
    content: |
      <html>
          <head>
              <title>Welcome to {{ apache_website_name }}!</title>
          </head>
          <body>
              <h1>Success!  The {{ apache_website_name }} server block is working!</h1>
          </body>
      </html>
    dest: "/var/www/{{ apache_website_name }}/index.html"
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Create basic php index
  ansible.builtin.copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Conecting PHP with MySQL</title>
      </head>
      <body>

      <?php
      // Database credentials
      $servername = "{{ mysql_db_host }}";
      $username = "{{ mysql_db_user }}";
      $password = "{{ mysql_db_pass }}";
      $database = "{{ mysql_db_name }}";

      // Create connection
      $conn = new mysqli($servername, $username, $password, $database);

      // Verify connection
      if ($conn->connect_error) {
          die("Falha na conexão: " . $conn->connect_error);
      }

      echo "Connection with MySQL sucessful!";

      // Close connection
      $conn->close();
      ?>

      </body>
      </html>
    dest: "/var/www/{{ apache_website_name }}/index.php"
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Add VirtualHost
  ansible.builtin.copy:
    dest: /etc/apache2/sites-available/{{ apache_website_name }}.conf
    content: |
      <VirtualHost *:80>
          ServerAdmin webmaster@localhost
          ServerName {{ apache_website_name }}
          ServerAlias www.{{ apache_website_name }}
          DocumentRoot /var/www/{{ apache_website_name }}
          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>
    mode: "0644"
    backup: true
  notify: Restart apache

- name: Enable website
  ansible.builtin.command:
    cmd: a2ensite {{ apache_website_name }}.conf
    creates: /etc/apache2/sites-enabled/{{ apache_website_name }}.conf
  notify: Restart apache

- name: Disable default website
  ansible.builtin.command:
    cmd: a2dissite 000-default.conf
    removes: /etc/apache2/sites-enabled/000-default.conf
  notify: Restart apache

- name: Validate configs
  ansible.builtin.command:
    cmd: apache2ctl configtest
  register: apache_validate_config
  changed_when: apache_validate_config.rc != 0

- name: Start and enable apache service
  ansible.builtin.systemd:
    name: apache2
    state: started
    enabled: true

- name: Run notified handlers
  ansible.builtin.meta: flush_handlers
