---
- name: Install mysql
  ansible.builtin.apt:
    name:
      - mysql-server-8.0
      - python3-pip
    state: present
    update_cache: true

- name: Install PyMySQL
  ansible.builtin.pip:
    name: PyMySQL
    state: present

- name: Copy mysql config
  ansible.builtin.copy:
    content: |
      [mysqld]
      datadir=/var/lib/mysql
      socket=/var/lib/mysql/mysql.sock
      user=mysql
      # Disabling symbolic-links is recommended to prevent assorted security risks
      symbolic-links=0
      port=3306

      [mysqld_safe]
      log-error=/var/log/mysqld.log
      pid-file=/var/run/mysqld/mysqld.pid
    dest: /etc/mysql/my.cnf
    mode: "0644"
    backup: true
  notify: Restart mysql

- name: Start and enable mysql
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true

- name: Run notified handlers
  ansible.builtin.meta: flush_handlers

# Exception message: 1698 Access denied for user root@localhost

- name: Create database
  community.mysql.mysql_db:
    name: example
    state: present

- name: Create database user
  community.mysql.mysql_user:
    name: user
    password: pass
    priv: "*.*:ALL"
    host: '%'
    state: present
