---
- name: Converge
  hosts: all
  diff: true
  become: true
  # pre_tasks:
  #   - name: "Get the non root remote user"
  #     ansible.builtin.set_fact:
  #       regular_user: "{{ ansible_facts.user_id }}"
  roles:
    - common
    - apache
