---
- name: "Install basic packages"
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - "ca-certificates>=20230311ubuntu0.{{ ansible_facts['distribution_version'] }}.1"
      - curl
      - git
      - gpg
      - htop
      - jq
      - openssh-client
      - python3-pip
      - python3-venv
      - vim
      - wget
    state: present
    update_cache: true
    cache_valid_time: "3600"

- name: "Add vim default configs"
  ansible.builtin.blockinfile:
    path: /etc/vim/vimrc.local
    block: |
      set scrolloff=0
    marker: '" {mark} ANSIBLE MANAGED BLOCK'
    mode: "0644"
    backup: true
    create: true

- name: "Check if reboot is required"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: common_reboot_required

- name: "Reboot machine"
  ansible.builtin.reboot:
  when: common_reboot_required.stat.exists
